const categories = [
  { id: "warm", name: "따뜻한 우동", icon: "🔥", displayOrder: 1, visible: true },
  { id: "cold", name: "차가운 메뉴", icon: "❄️", displayOrder: 2, visible: true },
  { id: "meal", name: "식사류", icon: "🍚", displayOrder: 3, visible: true },
  { id: "side", name: "사이드메뉴", icon: "🍢", displayOrder: 4, visible: true },
];

const menuItems = [
  {
    id: "warm-01",
    name: "가케우동",
    category: "warm",
    description: "따뜻한 가쓰오 육수에 쫄깃한 면을 담은 기본 우동입니다.",
    price: 7000,
    image: "images/menu-kake-udon.jpg",
    recommended: true,
    new: false,
    soldOut: false,
  },
  {
    id: "warm-02",
    name: "카레우동",
    category: "warm",
    description: "진한 카레 국물에 쫄깃한 면을 더한 든든한 한 그릇입니다.",
    price: 9000,
    image: "images/menu-curry-udon.jpg",
    recommended: false,
    new: true,
    soldOut: false,
  },
  {
    id: "cold-01",
    name: "자루우동",
    category: "cold",
    description: "차갑게 헹군 면을 진한 츠유에 찍어 먹는 시원한 우동입니다.",
    price: 8000,
    image: "images/menu-zaru-udon.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "cold-02",
    name: "붓카케우동",
    category: "cold",
    description: "차가운 면 위에 진한 육수를 부어 먹는 시원한 우동입니다.",
    price: 8500,
    image: "images/menu-bukkake-udon.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "meal-01",
    name: "유부초밥",
    category: "meal",
    description: "달콤한 유부 속에 밥을 채운 한입 크기 초밥입니다.",
    price: 5000,
    image: "images/menu-inari-sushi.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "meal-02",
    name: "오니기리 세트",
    category: "meal",
    description: "정성껏 빚은 주먹밥 세 종류로 구성된 세트입니다.",
    price: 6000,
    image: "images/menu-onigiri-set.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "side-01",
    name: "튀김모둠",
    category: "side",
    description: "바삭하게 튀긴 채소와 새우 튀김 모둠입니다.",
    price: 6000,
    image: "images/menu-tempura.jpg",
    recommended: true,
    new: false,
    soldOut: false,
  },
  {
    id: "side-02",
    name: "유부주머니",
    category: "side",
    description: "달콤 짭짤하게 조린 유부 주머니 사이드 메뉴입니다.",
    price: 4000,
    image: "images/menu-inari-pocket.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
];
