const bannerSlides = [
  { id: "banner-01", image: "images/하루우동_연출컷03.jpg", alt: "하루우동 매장 분위기 1" },
  { id: "banner-02", image: "images/하루우동_연출컷04.jpg", alt: "하루우동 매장 분위기 2" },
  { id: "banner-03", image: "images/하루우동_연출컷05.jpg", alt: "하루우동 매장 분위기 3" },
  { id: "banner-04", image: "images/하루우동_연출컷06.jpg", alt: "하루우동 매장 분위기 4" },
  { id: "banner-05", image: "images/하루우동_연출컷07.jpg", alt: "하루우동 매장 분위기 5" },
];

const categories = [
  { id: "warm", name: "따뜻한 우동", icon: "🔥", displayOrder: 1, visible: true },
  { id: "cold", name: "차가운 메뉴", icon: "❄️", displayOrder: 2, visible: true },
  { id: "meal", name: "식사류", icon: "🍚", displayOrder: 3, visible: true },
  { id: "side", name: "사이드메뉴", icon: "🍢", displayOrder: 4, visible: true },
];

const menuItems = [
  {
    id: "warm-01",
    name: "하루우동",
    category: "warm",
    description: "하루우동의 기본이 되는 담백한 우동입니다.",
    price: 7500,
    image: "images/하루우동.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "warm-02",
    name: "새우튀김우동",
    category: "warm",
    description: "바삭한 새우튀김을 올린 우동입니다.",
    price: 8900,
    image: "images/새우튀김우동.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "warm-03",
    name: "카라이(얼큰)우동",
    category: "warm",
    description: "얼큰하고 칼칼한 국물의 매운 우동입니다.",
    price: 9500,
    image: "images/얼큰하루우동.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "warm-04",
    name: "니쿠카레우동",
    category: "warm",
    description: "진한 카레 국물에 고기를 더한 우동입니다.",
    price: 10900,
    image: "images/니쿠카레우동.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "warm-05",
    name: "로제우동",
    category: "warm",
    description: "크리미한 로제 소스로 끓인 우동입니다.",
    price: 10900,
    image: "images/로제우동.jpg",
    recommended: false,
    stronglyRecommended: true,
    new: false,
    soldOut: false,
  },
  {
    id: "warm-06",
    name: "마라우동",
    category: "warm",
    description: "얼얼한 마라 향이 매력적인 우동입니다.",
    price: 11500,
    image: "images/마라우동.jpg",
    recommended: false,
    stronglyRecommended: true,
    new: false,
    soldOut: false,
  },
  {
    id: "warm-07",
    name: "샤브우동",
    category: "warm",
    description: "샤브샤브 고기를 곁들인 우동입니다.",
    price: 11500,
    image: "images/샤브우동.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "cold-01",
    name: "하루냉모밀",
    category: "cold",
    description: "시원하게 즐기는 냉 메밀 소바입니다.",
    price: 8500,
    image: "images/하루냉모밀.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "cold-02",
    name: "하루냉우동",
    category: "cold",
    description: "차갑게 헹궈낸 시원한 냉우동입니다.",
    price: 8500,
    image: "images/하루냉우동.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "cold-03",
    name: "들기름메밀면",
    category: "cold",
    description: "고소한 들기름 향의 냉메밀면입니다.",
    price: 9500,
    image: "images/들기름메밀면.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "meal-01",
    name: "돈토로(항정살)덮밥",
    category: "meal",
    description: "부드러운 항정살을 올린 덮밥입니다.",
    price: 11500,
    image: "images/돈토로(항정살)덮밥.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "meal-02",
    name: "특명란밥",
    category: "meal",
    description: "명란을 올린 하루우동의 특제 명란밥입니다.",
    price: 12500,
    image: "images/특명란밥.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "meal-03",
    name: "하루돈카츠",
    category: "meal",
    description: "바삭하게 튀긴 하루우동의 돈카츠입니다.",
    price: 9500,
    image: "images/하루돈가스.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "meal-04",
    name: "치즈카츠",
    category: "meal",
    description: "고소한 치즈가 가득 들어간 카츠입니다.",
    price: 12500,
    image: "images/치즈카츠.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "meal-05",
    name: "하루우동 세트",
    category: "meal",
    description: "하루우동에 모둠튀김·직화불고기·돈카츠 중 하나를 더한 세트입니다.",
    price: 10900,
    image: "images/하루우동 모둠튀김세트.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "meal-06",
    name: "샤브우동 카츠세트",
    category: "meal",
    description: "샤브우동에 카츠와 유부초밥을 더한 세트입니다.",
    price: 14500,
    image: "images/샤브우동 카츠세트.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "meal-07",
    name: "카라이(얼큰)우동 세트",
    category: "meal",
    description: "얼큰우동에 모둠튀김·직화불고기·돈카츠 중 하나를 더한 세트입니다.",
    price: 12900,
    image: "images/얼큰우동 모둠튀김세트.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "meal-08",
    name: "로제우동 세트",
    category: "meal",
    description: "로제우동에 모둠튀김·돈카츠 중 하나를 더한 세트입니다.",
    price: 13900,
    image: "images/로제우동 모둠튀김세트.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "meal-09",
    name: "니쿠카레우동 카츠세트",
    category: "meal",
    description: "니쿠카레우동에 카츠와 공기밥을 더한 세트입니다.",
    price: 14000,
    image: "images/니쿠카레우동 카츠세트.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "meal-10",
    name: "하루냉우동 세트",
    category: "meal",
    description: "하루냉우동에 모둠튀김·직화불고기·돈카츠 중 하나를 더한 세트입니다.",
    price: 11900,
    image: "images/냉우동 모둠튀김세트.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "meal-11",
    name: "하루냉모밀 세트",
    category: "meal",
    description: "하루냉모밀에 모둠튀김·직화불고기·돈카츠 중 하나를 더한 세트입니다.",
    price: 11900,
    image: "images/냉모밀 모둠튀김세트.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "meal-12",
    name: "들기름메밀면 세트",
    category: "meal",
    description: "들기름메밀면에 모둠튀김·직화불고기·돈카츠 중 하나를 더한 세트입니다.",
    price: 12900,
    image: "images/들기름메밀면 모둠튀김세트.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "side-01",
    name: "특명란밥 단품",
    category: "side",
    description: "명란을 올린 특제 명란밥 단품입니다.",
    price: 7500,
    image: "images/특명란밥 단품.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "side-02",
    name: "모둠튀김",
    category: "side",
    description: "다양한 재료로 튀겨낸 모둠튀김입니다.",
    price: 5000,
    image: "images/모둠튀김 단품.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "side-03",
    name: "직화불고기",
    category: "side",
    description: "직화로 구워낸 불고기 사이드입니다.",
    price: 5000,
    image: "images/직화불고기 단품.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "side-04",
    name: "카츠(추가 1p)",
    category: "side",
    description: "돈카츠를 1피스 추가하는 메뉴입니다.",
    price: 4000,
    image: "images/카츠 단품.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "side-05",
    name: "가라아게",
    category: "side",
    description: "바삭하게 튀긴 일본식 가라아게입니다.",
    price: 5000,
    image: "images/가라아게.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "side-06",
    name: "유부초밥(2p)",
    category: "side",
    description: "달콤한 유부초밥 2피스입니다.",
    price: 2500,
    image: "images/유부초밥 2P.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
  {
    id: "side-07",
    name: "새우튀김(2p)",
    category: "side",
    description: "바삭한 새우튀김 2피스입니다.",
    price: 2500,
    image: "images/새우튀김 2P.jpg",
    recommended: false,
    new: false,
    soldOut: false,
  },
];
